### ISSUE TITLE
Update firmware for floower

### ISSUE THREAD

**Issue by imseandavis** [jpraus/floower#1]
Following instructions on this page (https://github.com/jpraus/floower#connecting-flower-to-the-computer) leads to the flower slamming closed upon sketch upload compile completion then I get this message:

Sketch uses 1004283 bytes (76%) of program storage space. Maximum is 1310720 bytes.
Global variables use 36744 bytes (11%) of dynamic memory, leaving 290936 bytes for local variables. Maximum is 327680 bytes.
esptool.py v2.6
Serial port COM3
Connecting........_____....._____....._____....._____....._____....._____.....____An error occurred while uploading the sketch
_

A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header

Running a windows 10 latest PC with newest drivers based on recommended versions and verified USB-C data cable on port COM3.

**Comment by jpraus** [comment]
Hi! Let me know your Floower serial number.

**Comment by jpraus** [comment]
Do you have CP2102 drivers installed? Is your device recognized in Device Manager as CP210x device?

**Comment by NielsLeenheer** [comment]
I'm having the same problem, but from a Mac. 

```
esptool.py v2.6
Serial port /dev/cu.usbserial-0001
Connecting........_____....._____....._____....._____....._____....._____.....____An error occurred while uploading the sketch
_

A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header
```

I can use the Serial Monitor to see the debug information that the Floower is sending over the serial port. So there is not a problem with the right driver or port. Mine has serial #0020.

I've encountered this error before when playing around with other ESP32 boards and it usually means you have to hold down the Boot/Flash button.

**Comment by imseandavis** [comment]
> I'm having the same problem, but from a Mac.
> 
> ```
> esptool.py v2.6
> Serial port /dev/cu.usbserial-0001
> Connecting........_____....._____....._____....._____....._____....._____.....____An error occurred while uploading the sketch
> _
> 
> A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header
> ```
> 
> I can use the Serial Monitor to see the debug information that the Floower is sending over the serial port. So there is not a problem with the right driver or port. Mine has serial #0020.
> 
> I've encountered this error before when playing around with other ESP32 boards and it usually means you have to hold down the Boot/Flash button.

yeah, there's a way to get around it by soldering a cap onto the board but I don't want to take mine apart to find out or manually push a button for each update unless I absolutely have to. This thing breaks and my wife will have a meltdown, lol.

**Comment by imseandavis** [comment]
> Hi! Let me know your Floower serial number.

Serial Number: 0026

**Comment by imseandavis** [comment]
> Do you have CP2102 drivers installed? Is your device recognized in Device Manager as CP210x device?

Yes, x64 for Windows 10. Heres a screenshot of it being detected and functioning properly in Device Manager as well as detected by Arduino and assigned to COM3.

![image](https://user-images.githubusercontent.com/8854420/94584940-5400ad80-024d-11eb-8c79-e0f1410164a0.png)

![image](https://user-images.githubusercontent.com/8854420/94585018-6bd83180-024d-11eb-857f-834d4bfc615f.png)

**Comment by jpraus** [comment]
> > I'm having the same problem, but from a Mac.
> > ```
> > esptool.py v2.6
> > Serial port /dev/cu.usbserial-0001
> > Connecting........_____....._____....._____....._____....._____....._____.....____An error occurred while uploading the sketch
> > _
> > 
> > A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header
> > ```
> > 
> > 
> > I can use the Serial Monitor to see the debug information that the Floower is sending over the serial port. So there is not a problem with the right driver or port. Mine has serial #0020.
> > I've encountered this error before when playing around with other ESP32 boards and it usually means you have to hold down the Boot/Flash button.
> 
> yeah, there's a way to get around it by soldering a cap onto the board but I don't want to take mine apart to find out or manually push a button for each update unless I absolutely have to. This thing breaks and my wife will have a meltdown, lol.

It is equipped with auto-reset circuit so it should reset on the upload of the code. I use the same method to upload the original firmware. So I am relly puzzled why this is not working for you.

**Comment by jpraus** [comment]
Could you try to turn OFF the flower, plug in the cable and then try to upload the code?

**Comment by NielsLeenheer** [comment]
> Could you try to turn OFF the flower, plug in the cable and then try to upload the code?

That does not seem to make any difference. I've tried several time with varying time between uploading an inserting the cable, but I always get the same error (or that the port is not yet available, which means I was too late with inserting the cable).

**Comment by NielsLeenheer** [comment]
I've also tried to use `esptool` manually to connect to the device and read out the mac address, and that also fails with the same error:

```
$ esptool.py --port /dev/cu.usbserial-0001 read_mac
esptool.py v2.8
Serial port /dev/cu.usbserial-0001
Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to Espressif device: Timed out waiting for packet header
```

**Comment by imseandavis** [comment]
Any updates on how we can fix this, can't update my floower to use the app :(

**Comment by jpraus** [comment]
> > Could you try to turn OFF the flower, plug in the cable and then try to upload the code?
> 
> That does not seem to make any difference. I've tried several time with varying time between uploading an inserting the cable, but I always get the same error (or that the port is not yet available, which means I was too late with inserting the cable).

I meant to keep the flower OFF all the time, that will disconnect the battery to prevent interferences while uploading via serial. Did you tried it? The full process would be:

- Turn the flower OFF
- Plug in the USB-C data cable
- Start uploading sketch

All the Floowers are being programed via the USB interface so it definitelly worked before I've shipped it to you. What is your OS? The error you are getting is usually result of USB-UART bridge not working properly but since SN0026 logic board was made in factory with genuine componenets it does not make sense...

I am using Win10 or MacOS. I will try to to the same process on the different blank computer to see if I can reproduce the problem.

Do you ever worked with ESP32 boards? Do you have any ESP32 development board at hand?

**Comment by NielsLeenheer** [comment]
Flashing other ESP32's were never a problem, they use a different chip and driver. But...

I managed to flash mine! The problem was that my CP210x macOS drivers were not the latest version. After updating it worked. I went from version to 5.2 to 5.3.5.

**Comment by jpraus** [comment]
Excellent! Thank you for letting me know!
@imseandavis can you check if you have the latest driver installed?

**Comment by imseandavis** [comment]
I do, but will try from another computer as well as report back.

**Comment by imseandavis** [comment]
Everything went wonderful, apparently the x64 driver was the problem, used x32 and it was right as rain.

**Comment by jpraus** [comment]
Excellent! Thank you for letting me know!
