### ISSUE TITLE
When setting the Touch Sensitivity to high, it will continuously detect a long touch.

### ISSUE THREAD

**Issue by NielsLeenheer** [jpraus/floower#4]
When setting the touch sensitivity to high, the Floower will think that you are holding the leaf continuously. Perhaps 'high' (value of 55) is too high. 

The result is that the Floower will constantly enable Bluetooth pairing mode and the Floower will start blinking blue and stop responding to normal touches.

**Comment by jpraus** [comment]
Fixed in latest mobile app release
