### ISSUE TITLE
Floower Flasher crash MacOS

### ISSUE THREAD

**Issue by pmirabel** [jpraus/floower#6]
Hi! 

Just received and unboxed my Floower. Great work with the packaging 👏 !! _(though it could have been a little bit more ecofriendly :-))_
Can't wait to put my hand "in" it (in the code, at least).  

Unfortunately it came flashed with the 4.0 FW and  I want to upgrade it, but the flasher crash on my macbook.

I can give you the full report if needed.
Have a nice day.
Here is a chunk : 
``` log
Process:               Floower Flasher [12556]
Path:                  /private/var/folders/*/Floower Flasher.app/Contents/MacOS/Floower Flasher
Identifier:            io.floower.flasher
Version:               0.0.0 (???)
Code Type:             X86-64 (Native)
Parent Process:        Floower Flasher [12547]
Responsible:           Floower Flasher [12547]
User ID:               501

Date/Time:             2021-02-01 11:56:40.785 +0100
OS Version:            macOS 11.1 (20C69)
Report Version:        12
Bridge OS Version:     5.1 (18P3030)
Time Awake Since Boot: 420000 seconds (OMG 🙄 )
Time Since Wake:       2300 seconds

System Integrity Protection: disabled

Notes:                 Translocated Process

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
```

**Comment by jpraus** [comment]
Hi!

Thank you for reporting the crash. I can see you are running Big Sur. Do you have Intel or Apple Silicon Macbook?
Regarding the eco friendly, any idea how to improve it? And what exactly do you have in mind? The box and the foam?

**Comment by pmirabel** [comment]
Thank you for the quick answer!! 
I use an intel macbook (macbook air 2019). 

I am currently trying to upgrade the floower through "manual" (arduino IDE) way, and found some issues... linked to big sure again. I will let you know soon as I manage to upgrate it (Mainly struggling with ESP board version for aduino IDE: I need to use a "dev" release (min .working version is [1.0.5rc4](https://github.com/espressif/arduino-esp32/releases/tag/1.0.5-rc4), but it seems that some API have change, but not sure.).
/edit: see https://github.com/espressif/esptool/issues/540#issuecomment-747185562 

Regarding the packaging, I was just sharing my second feeling (after the "waoow, that's some trully nice packaging" ... I don't really know if there are way to improve that... 
This is not very constructive sorry :-) But as you are  selling a "cyborg flower", maybe a more "natural" packaging could please customer as well ... 

have a nice day !

**Comment by pmirabel** [comment]
About the "manual upgrade" method on MacOS Big Sur. 
I am currently stuck, will take some time later to get this clear (using a widows computer waiting for that!  

Here is what I found :  
- Since Big Sur ESPTOOL 1.0.4 won't work anymore (still unclear why, related to pyserial?) : https://github.com/espressif/esptool/issues/540  
- 1.0.5 version fix that, but `analogSetCycles`, `analogSetSamples` seems to be missing : https://esp32.com/viewtopic.php?t=11923  

This lead to :  
```
sketch/floower.cpp: In member function 'void Floower::init()':
floower.cpp:54:20: error: 'analogSetCycles' was not declared in this scope
   analogSetCycles(8); // num of cycles per sample, 8 is default optimal
                    ^
floower.cpp:55:21: error: 'analogSetSamples' was not declared in this scope
   analogSetSamples(1); // num of samples
                     ^
```

A the moment, one possible fix could be to implement it, but still not sure!

See you

**Comment by pmirabel** [comment]
👍 thx!
