### ISSUE TITLE
Update App for MacOS isn't working.

### ISSUE THREAD

**Issue by zuidwijk** [jpraus/floower#8]
I wanted to download the updater to update my Floower.
On opening, it remains black:
<img width="862" alt="Schermafbeelding 2021-11-22 om 18 47 09" src="https://user-images.githubusercontent.com/10123063/142910450-506f324b-15e0-4e8c-8ac5-0b5f425b29e1.png">

MacBook Pro M1 Pro 2021 with latest macOS Monterey (12.0.1).

**Comment by zuidwijk** [comment]
Maybe updating via CLI (esptool)?

**Comment by jpraus** [comment]
Thanks for reporting! Working on it at the moment. As a workaround, you can set up a PlatformIO project from the source code and upload it manually.

**Comment by zuidwijk** [comment]
Ah ok, I'll have to look into platformio, as I'm currently only using esptool for flashing esp's.

**Comment by jpraus** [comment]
You can do that as well, run:
` 0x10000 bin/floower-esp32.ino.bin 0x8000 bin/floower-esp32.ino.partitions.bin`
the files can be found https://github.com/jpraus/floower/tree/master/src/tools/planter-rpi/bin

**Comment by jpraus** [comment]
Fixed, download the latest Flasher.

**Comment by jpraus** [comment]
It was caused by OS Monterey, had to upgrade some libraries :)

**Comment by zuidwijk** [comment]
Thanks!

**Comment by zuidwijk** [comment]
Working perfect:
<img width="862" alt="Schermafbeelding 2021-11-26 om 20 19 06" src="https://user-images.githubusercontent.com/10123063/143623102-ba489eae-50a9-4b64-ad8d-cfde802fef39.png">

Before flashing, I've got a quick short question: Is Flooware 10 compatible with all flowers? I've got sn 243.
Flooware 8 states "Support for the new generation of Floowers with stepper motor (from Serial Number 400)"
That get me confused ... 

(no need to open an issue, just a quick question)

**Comment by jpraus** [comment]
Yes, it’s backward comptible to deliver new features to all Floowers out there :-)
