### ISSUE TITLE
Missing AccelStepper.h

### ISSUE THREAD

**Issue by berendhaan** [jpraus/floower#9]
Hi,

First, I really like the Floower 😊. It's a great addition to the living room.

I was trying to compile the source code, but I'm running into some issues.
`Floorer.h ` has a reference to `AccelStepper.h` but that file seems to be missing in the repo.

Am I missing something or did you forget it to push it to the repo?

**Comment by jpraus** [comment]
Hi, thank you and welcome!

I removed the AccelStepper dependency and replaced it with an internal library, but forgot to remove it from the header file. Looks like my IDE does not care... Fixed! Let me know if you run into any troublem.
